version: "3"
services:
  client_web:
    build:
      context: "./web"
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    depends_on:
      - server
    restart: always
  server:
    build:
      context: "./server/"
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    restart: always
